GET http://localhost:5000/genres/10
Accept: application/json

###

DELETE http://localhost:5000/reviews/1
Content-Type: application/json

###

PUT http://localhost:5000/genres/1
Content-Type: application/json

{
  "id": 1,
  "user": "Thomas",
  "rating": 5,
  "book_id": 1
}

###

POST http://localhost:5000/movies/
Content-Type: application/json

{
  "trailer": "Thomas",
  "title": 15,
  "id": 144,
  "description": 56,
  "year": 15,
  "rating": 8
}
